// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHCDtjbv-weOL98kTGlX6ae9ZlLChVesA',
    appId: '1:14297823681:web:f05896c462880c20461740',
    messagingSenderId: '14297823681',
    projectId: 'notechat-b4ce1',
    authDomain: 'notechat-b4ce1.firebaseapp.com',
    storageBucket: 'notechat-b4ce1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3nFAJgYiuS5H-rxaPNMiNJGJvFRyHeg',
    appId: '1:14297823681:android:2bf636d22e704efa461740',
    messagingSenderId: '14297823681',
    projectId: 'notechat-b4ce1',
    storageBucket: 'notechat-b4ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhy6EW9x7NxsDW3951vsBO2HDQC4X5lEY',
    appId: '1:14297823681:ios:90bf7f34f2b4cf6e461740',
    messagingSenderId: '14297823681',
    projectId: 'notechat-b4ce1',
    storageBucket: 'notechat-b4ce1.firebasestorage.app',
    iosBundleId: 'com.azcoder.notechat.noteChat',
  );
}
